title: Aurora Selestial
description: Jelajahi dan pahami alam semesta
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman

links:
  trakteer: https://trakteer.id/auroraselestial/tip
  instagram: https://www.instagram.com/auroraselestial
  tiktok: https://www.tiktok.com/@auroraselestial
  youtube: https://www.youtube.com/channel/UCycXcIM_44KVC7aR2KYYVdw
  gdrive: https://drive.google.com/drive/folders/1gOh3L8opXjgh8zk2feDbA4XLWXYkJ8Ze?usp=sharing
  email: https://auroraselestial.github.io
  about: ./about.html#about